language: php

jobs:
  include:
    - php: 7.3
      env: SYMFONY_VERSION='4.4.*'
    - php: 7.4
      env: SYMFONY_VERSION='5.1.*'
    - php: 8.0snapshot
      env: SYMFONY_VERSION='5.2.*'

before_script:
  - |
    if [ "$SYMFONY_VERSION" != "" ]; then
      sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
    fi;
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - composer install --dev

script: vendor/bin/phpunit
